import { MatchSubPlan, PlannedSub } from '../types';

export const DEFAULT_MATCH_MINUTES = 60;
export const QUARTERS = 4 as const;

export type Quarter = 1 | 2 | 3 | 4;

export function emptySubPlan(matchMinutes = DEFAULT_MATCH_MINUTES): MatchSubPlan {
  return {
    matchMinutes,
    quarters: QUARTERS,
    swaps: [],
    autoGenerated: false,
  };
}

export function minutesPerQuarter(plan: Pick<MatchSubPlan, 'matchMinutes'>): number {
  const total = plan.matchMinutes > 0 ? plan.matchMinutes : DEFAULT_MATCH_MINUTES;
  return total / QUARTERS;
}

/** Apply planned swaps for a given afterQuarter onto a slot→player lineup. */
export function applySwapsToLineup(
  lineup: Record<string, string>,
  swaps: PlannedSub[],
  afterQuarter: 1 | 2 | 3
): Record<string, string> {
  const next = { ...lineup };
  for (const swap of swaps.filter(s => s.afterQuarter === afterQuarter)) {
    const slot = Object.entries(next).find(([, pid]) => pid === swap.playerOut)?.[0];
    if (!slot) continue;
    if (Object.values(next).includes(swap.playerIn)) continue;
    next[slot] = swap.playerIn;
  }
  return next;
}

/** Lineup on the pitch at the start of each quarter (1–4). */
export function lineupsByQuarter(
  startingLineup: Record<string, string>,
  swaps: PlannedSub[]
): Record<Quarter, Record<string, string>> {
  let current = { ...startingLineup };
  const result = { 1: { ...current } } as Record<Quarter, Record<string, string>>;
  for (const after of [1, 2, 3] as const) {
    current = applySwapsToLineup(current, swaps, after);
    result[(after + 1) as Quarter] = { ...current };
  }
  return result;
}

/**
 * Projected minutes this match from a sub plan (starters + planned swaps).
 * Everyone in `squadIds` is included (0 if unused).
 */
export function projectMatchMinutes(
  startingLineup: Record<string, string>,
  plan: MatchSubPlan,
  squadIds: string[]
): Record<string, number> {
  const perQ = minutesPerQuarter(plan);
  const byQ = lineupsByQuarter(startingLineup, plan.swaps || []);
  const minutes: Record<string, number> = {};
  squadIds.forEach(id => {
    minutes[id] = 0;
  });
  Object.values(startingLineup).forEach(id => {
    if (id && minutes[id] === undefined) minutes[id] = 0;
  });

  ([1, 2, 3, 4] as Quarter[]).forEach(q => {
    Object.values(byQ[q]).forEach(id => {
      if (!id) return;
      minutes[id] = (minutes[id] || 0) + perQ;
    });
  });

  const rounded: Record<string, number> = {};
  Object.entries(minutes).forEach(([id, m]) => {
    rounded[id] = Math.round(m);
  });
  return rounded;
}

/** Fairness summary for UI hints. */
export function planFairnessStats(projected: Record<string, number>, squadIds: string[]) {
  const values = squadIds.map(id => projected[id] || 0);
  if (values.length === 0) {
    return { min: 0, max: 0, avg: 0, unused: [] as string[], spread: 0 };
  }
  const min = Math.min(...values);
  const max = Math.max(...values);
  const avg = values.reduce((a, b) => a + b, 0) / values.length;
  const unused = squadIds.filter(id => (projected[id] || 0) === 0);
  return { min, max, avg, unused, spread: max - min };
}
