B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=12.80
@EndOfDesignText@
' Quarter-based sub plan matching reference/lib/subPlan.ts + fair auto swaps.
' Shape: { matchMinutes, quarters: 4, swaps: [{afterQuarter, playerOut, playerIn, outName, inName}],
'   moves: [{afterQuarter, slotA, slotB, nameA, nameB}], layout: {slotId: {x, y}}, autoGenerated }
' moves exchange two slots from that break onward (not a sub). layout is display % for dragged markers.

Sub Process_Globals
	Public Const DEFAULT_MATCH_MINUTES As Int = 60
	Public Const QUARTERS As Int = 4
End Sub

Public Sub EmptyPlan(matchMinutes As Int) As Map
	Dim m As Map
	m.Initialize
	If matchMinutes <= 0 Then matchMinutes = DEFAULT_MATCH_MINUTES
	m.Put("matchMinutes", matchMinutes)
	m.Put("quarters", QUARTERS)
	Dim swaps As List
	swaps.Initialize
	m.Put("swaps", swaps)
	Dim moves As List
	moves.Initialize
	m.Put("moves", moves)
	Dim layout As Map
	layout.Initialize
	m.Put("layout", layout)
	m.Put("autoGenerated", False)
	Dim targets As Map
	targets.Initialize
	m.Put("playTargets", targets)
	Return m
End Sub

Public Sub MinutesPerQuarter(plan As Map) As Double
	Dim total As Int = plan.GetDefault("matchMinutes", DEFAULT_MATCH_MINUTES)
	If 0 >= total Then total = DEFAULT_MATCH_MINUTES
	Return total / QUARTERS
End Sub

Public Sub ApplySwapsToLineup(lineup As Map, swaps As List, afterQuarter As Int) As Map
	Dim nextMap As Map = CopyMap(lineup)
	For Each swap As Map In swaps
		If afterQuarter = swap.GetDefault("afterQuarter", 0) Then
			Dim playerOut As String = swap.GetDefault("playerOut", "")
			Dim playerIn As String = swap.GetDefault("playerIn", "")
			Dim slot As String = SlotForPlayer(nextMap, playerOut, "")
			If slot <> "" Then
				If ValuesContain(nextMap, playerIn) = False Then
					nextMap.Put(slot, playerIn)
				End If
			End If
		End If
	Next
	Return nextMap
End Sub

' Subs at a break are applied first, then position moves at that same break.
Public Sub LineupsByQuarter(startingLineup As Map, swaps As List, moves As List) As Map
	Dim result As Map
	result.Initialize
	Dim current As Map = CopyMap(startingLineup)
	result.Put("1", CopyMap(current))
	Dim afterQ As Int
	For afterQ = 1 To 3
		current = ApplySwapsToLineup(current, swaps, afterQ)
		current = ApplyMovesToLineup(current, moves, afterQ)
		result.Put("" & (afterQ + 1), CopyMap(current))
	Next
	Return result
End Sub

' Exchange slot occupants. Empty slots are removed so a blank does not stay in the map.
Public Sub ExchangeSlots(lineup As Map, slotA As String, slotB As String)
	If lineup.IsInitialized = False Then Return
	If slotA = "" Or slotB = "" Or slotA = slotB Then Return
	Dim a As String = "" & lineup.GetDefault(slotA, "")
	Dim b As String = "" & lineup.GetDefault(slotB, "")
	If a = "null" Then a = ""
	If b = "null" Then b = ""
	If b = "" Then
		lineup.Remove(slotA)
	Else
		lineup.Put(slotA, b)
	End If
	If a = "" Then
		lineup.Remove(slotB)
	Else
		lineup.Put(slotB, a)
	End If
End Sub

Public Sub ApplyMovesToLineup(lineup As Map, moves As List, afterQuarter As Int) As Map
	Dim nextMap As Map = CopyMap(lineup)
	If moves.IsInitialized = False Then Return nextMap
	Dim i As Int
	For i = 0 To moves.Size - 1
		Dim raw As Object = moves.Get(i)
		If Not(raw Is Map) Then Continue
		Dim mv As Map = raw
		If afterQuarter <> mv.GetDefault("afterQuarter", 0) Then Continue
		ExchangeSlots(nextMap, "" & mv.GetDefault("slotA", ""), "" & mv.GetDefault("slotB", ""))
	Next
	Return nextMap
End Sub

Public Sub ProjectMatchMinutes(startingLineup As Map, plan As Map, squadIds As List) As Map
	Dim perQ As Double = MinutesPerQuarter(plan)
	Dim swaps As List = plan.GetDefault("swaps", EmptyList)
	Dim moves As List = plan.GetDefault("moves", EmptyList)
	If moves.IsInitialized = False Then moves = EmptyList
	Dim byQ As Map = LineupsByQuarter(startingLineup, swaps, moves)
	Dim minutes As Map
	minutes.Initialize
	Dim allowed As Map
	allowed.Initialize
	' Only real squad / member ids. Lineup junk must not become a "player".
	For Each id As Object In squadIds
		Dim sid As String = "" & id
		If sid <> "" And sid <> "null" Then
			minutes.Put(sid, 0)
			allowed.Put(sid, True)
		End If
	Next
	Dim q As Int
	For q = 1 To 4
		Dim lineupQ As Map = byQ.Get("" & q)
		If lineupQ.IsInitialized = False Then Continue
		Dim seen As Map
		seen.Initialize
		For Each slotKey As String In lineupQ.Keys
			Dim pid As String = "" & lineupQ.Get(slotKey)
			If pid = "" Or pid = "null" Then Continue
			If allowed.ContainsKey(pid) = False Then Continue
			' One person, one slot's worth of minutes, even if the value is repeated.
			If seen.ContainsKey(pid) Then Continue
			seen.Put(pid, True)
			Dim soFar As Double = minutes.GetDefault(pid, 0)
			minutes.Put(pid, soFar + perQ)
		Next
	Next
	Dim rounded As Map
	rounded.Initialize
	For Each k As String In minutes.Keys
		rounded.Put(k, Round(minutes.Get(k)))
	Next
	Return rounded
End Sub

' Players in known formation slots. Skips blanks, non-members, and repeats.
' memberIds: map whose keys are club member ids (a name-by-id map is fine).
Public Sub MemberIdsInSlots(lineup As Map, formation As String, memberIds As Map) As List
	Dim out As List
	out.Initialize
	If lineup.IsInitialized = False Then Return out
	Dim formName As String = formation
	If formName = "" Then formName = modFormations.DefaultFormationForSize(11)
	Dim positions As List = modFormations.GetPositions(formName)
	Dim seen As Map
	seen.Initialize
	Dim i As Int
	For i = 0 To positions.Size - 1
		Dim p As Map = positions.Get(i)
		Dim posId As String = "" & p.GetDefault("id", "")
		If posId = "" Then Continue
		Dim pid As String = "" & lineup.GetDefault(posId, "")
		If pid = "" Or pid = "null" Then Continue
		If memberIds.IsInitialized = False Or memberIds.ContainsKey(pid) = False Then Continue
		If seen.ContainsKey(pid) Then Continue
		seen.Put(pid, True)
		out.Add(pid)
	Next
	Return out
End Sub

' playTargets: optional map playerId -> target quarters (1–4). Default 2 (half a game).
' Auto fair swaps players above their target off for those below target (up to maxSubsPerBreak each break).
Public Sub BuildFairQuarterPlan(confirmedSquad As List, startingLineup As Map, _
		nameById As Map, matchMinutes As Int, maxSubsPerBreak As Int) As Map
	Return BuildFairQuarterPlanWithTargets(confirmedSquad, startingLineup, nameById, matchMinutes, maxSubsPerBreak, EmptyMap2, "")
End Sub

Public Sub BuildFairQuarterPlanWithTargets(confirmedSquad As List, startingLineup As Map, _
		nameById As Map, matchMinutes As Int, maxSubsPerBreak As Int, playTargets As Map, formation As String) As Map
	Dim plan As Map = EmptyPlan(matchMinutes)
	If startingLineup.IsInitialized = False Or startingLineup.Size = 0 Then
		plan.Put("error", "Set a starting lineup first.")
		Return plan
	End If
	If maxSubsPerBreak < 1 Then maxSubsPerBreak = 2
	If playTargets.IsInitialized = False Then playTargets.Initialize
	plan.Put("playTargets", CopyMap(playTargets))
	
	Dim squadIds As List
	squadIds.Initialize
	For Each mem As Map In confirmedSquad
		Dim mid As String = "" & mem.Get("id")
		If mid <> "" And mid <> "null" Then squadIds.Add(mid)
	Next
	If squadIds.Size = 0 Then
		Dim slotted As List = MemberIdsInSlots(startingLineup, formation, nameById)
		Dim s As Int
		For s = 0 To slotted.Size - 1
			squadIds.Add(slotted.Get(s))
		Next
	End If
	
	Dim perQ As Double = MinutesPerQuarter(plan)
	Dim swaps As List
	swaps.Initialize
	Dim workingLineup As Map = CopyMap(startingLineup)
	Dim draftPlan As Map = EmptyPlan(matchMinutes)
	
	Dim afterQ As Int
	For afterQ = 1 To 3
		draftPlan.Put("swaps", CopyListOfMaps(swaps))
		Dim projected As Map = ProjectMatchMinutes(startingLineup, draftPlan, squadIds)
		
		Dim onPitch As List = MemberIdsInSlots(workingLineup, formation, nameById)
		Dim onBench As List
		onBench.Initialize
		For Each sid As String In squadIds
			If onPitch.IndexOf(sid) = -1 Then onBench.Add(sid)
		Next
		If onBench.Size = 0 Or onPitch.Size = 0 Then Exit
		
		' Prefer: take off those at/above target; bring on those below (unused first).
		Dim surplus As List
		surplus.Initialize
		Dim needy As List
		needy.Initialize
		Dim i As Int
		For i = 0 To onPitch.Size - 1
			Dim pOut As String = onPitch.Get(i)
			Dim tgtOut As Int = TargetQuartersFor(playTargets, pOut)
			If projected.GetDefault(pOut, 0) >= Round(tgtOut * perQ) Then surplus.Add(pOut)
		Next
		For i = 0 To onBench.Size - 1
			Dim pIn As String = onBench.Get(i)
			Dim tgtIn As Int = TargetQuartersFor(playTargets, pIn)
			If projected.GetDefault(pIn, 0) < Round(tgtIn * perQ) Then needy.Add(pIn)
		Next
		' If nobody is "needy" but someone has 0', still rotate to get them on.
		If needy.Size = 0 Then
			For i = 0 To onBench.Size - 1
				Dim p0 As String = onBench.Get(i)
				If 0 = projected.GetDefault(p0, 0) Then needy.Add(p0)
			Next
		End If
		If needy.Size = 0 Then Exit
		' Only take someone off who is already at/above target; if none, take highest minutes to free a slot for unused players.
		If surplus.Size = 0 Then
			Dim hasUnused As Boolean = False
			For i = 0 To needy.Size - 1
				If 0 = projected.GetDefault(needy.Get(i), 0) Then
					hasUnused = True
					Exit
				End If
			Next
			If hasUnused = False Then Exit
			surplus = SortIdsByMinutesDesc(onPitch, projected)
		End If
		
		Dim sortedPitch As List = SortIdsByMinutesDesc(surplus, projected)
		Dim sortedBench As List = SortIdsByMinutesAsc(needy, projected)
		Dim swapCount As Int = Min(Min(sortedPitch.Size, sortedBench.Size), maxSubsPerBreak)
		For i = 0 To swapCount - 1
			Dim outId As String = sortedPitch.Get(i)
			Dim inId As String = sortedBench.Get(i)
			Dim swap As Map
			swap.Initialize
			swap.Put("afterQuarter", afterQ)
			swap.Put("playerOut", outId)
			swap.Put("playerIn", inId)
			swap.Put("outName", nameById.GetDefault(outId, "Unknown"))
			swap.Put("inName", nameById.GetDefault(inId, "Unknown"))
			swaps.Add(swap)
			Dim slot As String = SlotForPlayer(workingLineup, outId, formation)
			If slot <> "" Then workingLineup.Put(slot, inId)
		Next
	Next
	
	plan.Put("swaps", swaps)
	plan.Put("autoGenerated", True)
	Dim projectedFinal As Map = ProjectMatchMinutes(startingLineup, plan, squadIds)
	plan.Put("projectedMinutes", projectedFinal)
	Return plan
End Sub

Public Sub TargetQuartersFor(playTargets As Map, playerId As String) As Int
	Dim q As Int = 2
	If playTargets.IsInitialized And playTargets.ContainsKey(playerId) Then
		q = playTargets.Get(playerId)
	End If
	If q < 1 Then q = 1
	If q > 4 Then q = 4
	Return q
End Sub

Public Sub FormatPlanLines(plan As Map, nameById As Map) As List
	Dim lines As List
	lines.Initialize
	Dim swaps As List = plan.GetDefault("swaps", EmptyList)
	If swaps.Size = 0 Then
		lines.Add("No quarter swaps planned.")
		Return lines
	End If
	Dim afterQ As Int
	For afterQ = 1 To 3
		Dim bucket As List
		bucket.Initialize
		For Each swap As Map In swaps
			If afterQ = swap.GetDefault("afterQuarter", 0) Then bucket.Add(swap)
		Next
		If bucket.Size > 0 Then
			Dim line As String = "After Q" & afterQ & ": "
			For Each s As Map In bucket
				Dim outN As String = s.GetDefault("outName", nameById.GetDefault(s.GetDefault("playerOut", ""), "?"))
				Dim inN As String = s.GetDefault("inName", nameById.GetDefault(s.GetDefault("playerIn", ""), "?"))
				line = line & outN & " -> " & inN & "; "
			Next
			lines.Add(line)
		End If
	Next
	Return lines
End Sub

Private Sub SortIdsByMinutesDesc(ids As List, minutes As Map) As List
	Dim out As List = CopyStrList(ids)
	Dim i, j As Int
	For i = 0 To out.Size - 2
		For j = i + 1 To out.Size - 1
			Dim a As String = out.Get(i)
			Dim b As String = out.Get(j)
			If minutes.GetDefault(b, 0) > minutes.GetDefault(a, 0) Then
				out.Set(i, b)
				out.Set(j, a)
			End If
		Next
	Next
	Return out
End Sub

Private Sub SortIdsByMinutesAsc(ids As List, minutes As Map) As List
	Dim out As List = CopyStrList(ids)
	Dim i, j As Int
	For i = 0 To out.Size - 2
		For j = i + 1 To out.Size - 1
			Dim a As String = out.Get(i)
			Dim b As String = out.Get(j)
			If minutes.GetDefault(b, 0) < minutes.GetDefault(a, 0) Then
				out.Set(i, b)
				out.Set(j, a)
			End If
		Next
	Next
	Return out
End Sub

Private Sub SlotForPlayer(lineup As Map, playerId As String, formation As String) As String
	If playerId = "" Then Return ""
	' Prefer a real formation slot so a stray map entry cannot steal the swap.
	If formation <> "" Then
		Dim positions As List = modFormations.GetPositions(formation)
		Dim i As Int
		For i = 0 To positions.Size - 1
			Dim p As Map = positions.Get(i)
			Dim posId As String = "" & p.GetDefault("id", "")
			If posId <> "" And ("" & lineup.GetDefault(posId, "")) = playerId Then Return posId
		Next
		Return ""
	End If
	For Each k As String In lineup.Keys
		If ("" & lineup.Get(k)) = playerId Then Return k
	Next
	Return ""
End Sub

Private Sub ValuesContain(lineup As Map, playerId As String) As Boolean
	If playerId = "" Then Return False
	For Each k As String In lineup.Keys
		If ("" & lineup.Get(k)) = playerId Then Return True
	Next
	Return False
End Sub

Private Sub CopyMap(src As Map) As Map
	Dim m As Map
	m.Initialize
	If src.IsInitialized Then
		For Each k As String In src.Keys
			m.Put(k, src.Get(k))
		Next
	End If
	Return m
End Sub

Private Sub CopyStrList(src As List) As List
	Dim out As List
	out.Initialize
	For Each o As Object In src
		out.Add(o)
	Next
	Return out
End Sub

Private Sub CopyListOfMaps(src As List) As List
	Dim out As List
	out.Initialize
	For Each m As Map In src
		out.Add(CopyMap(m))
	Next
	Return out
End Sub

Private Sub EmptyList As List
	Dim l As List
	l.Initialize
	Return l
End Sub

' Season minutes already played (completed and live). Same clock as a single match:
' kick-off, halves, and subs. Stored stats / the sub plan are fallbacks only.
Public Sub SeasonMinutesForPlayer(clubId As String, playerId As String, matches As List) As Int
	Dim total As Int = 0
	If playerId = "" Then Return 0
	Dim i As Int
	For i = 0 To matches.Size - 1
		Dim m As Map = matches.Get(i)
		If m.GetDefault("clubId", "") <> clubId Then Continue
		Dim status As String = m.GetDefault("status", "")
		If status <> "COMPLETED" And status <> "LIVE" Then Continue
		Dim feed As Map = modAppState.CalculateMatchMinutes(m)
		If feed.IsInitialized And feed.Size > 0 Then
			Dim played As Int = 0
			Try
				played = feed.GetDefault(playerId, 0)
			Catch
				played = 0
			End Try
			If played > 0 Then total = total + played
			Continue
		End If
		Dim stored As Int = -1
		Dim psMap As Map = m.GetDefault("playerStats", EmptyMap2)
		If psMap.IsInitialized And psMap.ContainsKey(playerId) Then
			Dim ps As Map = psMap.Get(playerId)
			Try
				stored = ps.GetDefault("minutesPlayed", -1)
			Catch
				stored = -1
			End Try
		End If
		If stored >= 0 Then
			total = total + stored
			Continue
		End If
		' No feed clock — project from the planned subs.
		Dim lineup As Map = m.GetDefault("lineup", m.GetDefault("tacticalLineup", EmptyMap2))
		Dim plan As Map = m.GetDefault("subPlan", EmptyPlan(DEFAULT_MATCH_MINUTES))
		If lineup.IsInitialized = False Or lineup.Size = 0 Then Continue
		Dim squadIds As List
		squadIds.Initialize
		squadIds.Add(playerId)
		Dim mins As Map = ProjectMatchMinutes(lineup, plan, squadIds)
		total = total + mins.GetDefault(playerId, 0)
	Next
	Return total
End Sub

Private Sub EmptyMap2 As Map
	Dim m As Map
	m.Initialize
	Return m
End Sub
