B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=12.80
@EndOfDesignText@
' Quarter-based sub plan matching reference/lib/subPlan.ts + fair auto swaps.
' Shape: { matchMinutes, quarters: 4, swaps: [{afterQuarter, playerOut, playerIn, outName, inName}], autoGenerated }

Sub Process_Globals
	Public Const DEFAULT_MATCH_MINUTES As Int = 60
	Public Const QUARTERS As Int = 4
End Sub

Public Sub EmptyPlan(matchMinutes As Int) As Map
	Dim m As Map
	m.Initialize
	If matchMinutes <= 0 Then matchMinutes = DEFAULT_MATCH_MINUTES
	m.Put("matchMinutes", matchMinutes)
	m.Put("quarters", QUARTERS)
	Dim swaps As List
	swaps.Initialize
	m.Put("swaps", swaps)
	m.Put("autoGenerated", False)
	Return m
End Sub

Public Sub MinutesPerQuarter(plan As Map) As Double
	Dim total As Int = plan.GetDefault("matchMinutes", DEFAULT_MATCH_MINUTES)
	If 0 >= total Then total = DEFAULT_MATCH_MINUTES
	Return total / QUARTERS
End Sub

Public Sub ApplySwapsToLineup(lineup As Map, swaps As List, afterQuarter As Int) As Map
	Dim nextMap As Map = CopyMap(lineup)
	For Each swap As Map In swaps
		If afterQuarter = swap.GetDefault("afterQuarter", 0) Then
			Dim playerOut As String = swap.GetDefault("playerOut", "")
			Dim playerIn As String = swap.GetDefault("playerIn", "")
			Dim slot As String = SlotForPlayer(nextMap, playerOut)
			If slot <> "" Then
				If ValuesContain(nextMap, playerIn) = False Then
					nextMap.Put(slot, playerIn)
				End If
			End If
		End If
	Next
	Return nextMap
End Sub

Public Sub LineupsByQuarter(startingLineup As Map, swaps As List) As Map
	Dim result As Map
	result.Initialize
	Dim current As Map = CopyMap(startingLineup)
	result.Put("1", CopyMap(current))
	Dim afterQ As Int
	For afterQ = 1 To 3
		current = ApplySwapsToLineup(current, swaps, afterQ)
		result.Put("" & (afterQ + 1), CopyMap(current))
	Next
	Return result
End Sub

Public Sub ProjectMatchMinutes(startingLineup As Map, plan As Map, squadIds As List) As Map
	Dim perQ As Double = MinutesPerQuarter(plan)
	Dim swaps As List = plan.GetDefault("swaps", EmptyList)
	Dim byQ As Map = LineupsByQuarter(startingLineup, swaps)
	Dim minutes As Map
	minutes.Initialize
	For Each id As String In squadIds
		minutes.Put(id, 0)
	Next
	For Each pid As String In startingLineup.Values
		If pid <> "" And minutes.ContainsKey(pid) = False Then minutes.Put(pid, 0)
	Next
	Dim q As Int
	For q = 1 To 4
		Dim lineupQ As Map = byQ.Get("" & q)
		For Each pid2 As String In lineupQ.Values
			If pid2 <> "" Then
				minutes.Put(pid2, minutes.GetDefault(pid2, 0) + perQ)
			End If
		Next
	Next
	Dim rounded As Map
	rounded.Initialize
	For Each k As String In minutes.Keys
		rounded.Put(k, Round(minutes.Get(k)))
	Next
	Return rounded
End Sub

Public Sub BuildFairQuarterPlan(confirmedSquad As List, startingLineup As Map, _
		nameById As Map, matchMinutes As Int, maxSubsPerBreak As Int) As Map
	Dim plan As Map = EmptyPlan(matchMinutes)
	If startingLineup.IsInitialized = False Or startingLineup.Size = 0 Then
		plan.Put("error", "Set a starting lineup first.")
		Return plan
	End If
	If maxSubsPerBreak < 1 Then maxSubsPerBreak = 2
	
	Dim squadIds As List
	squadIds.Initialize
	For Each mem As Map In confirmedSquad
		squadIds.Add(mem.Get("id"))
	Next
	If squadIds.Size = 0 Then
		For Each pid As String In startingLineup.Values
			If pid <> "" And squadIds.IndexOf(pid) = -1 Then squadIds.Add(pid)
		Next
	End If
	
	Dim swaps As List
	swaps.Initialize
	Dim workingLineup As Map = CopyMap(startingLineup)
	Dim draftPlan As Map = EmptyPlan(matchMinutes)
	
	Dim afterQ As Int
	For afterQ = 1 To 3
		draftPlan.Put("swaps", CopyListOfMaps(swaps))
		Dim projected As Map = ProjectMatchMinutes(startingLineup, draftPlan, squadIds)
		
		Dim onPitch As List
		onPitch.Initialize
		Dim onBench As List
		onBench.Initialize
		For Each pid As String In workingLineup.Values
			If pid <> "" Then onPitch.Add(pid)
		Next
		For Each sid As String In squadIds
			If onPitch.IndexOf(sid) = -1 Then onBench.Add(sid)
		Next
		If onBench.Size = 0 Or onPitch.Size = 0 Then Exit
		
		Dim sortedPitch As List = SortIdsByMinutesDesc(onPitch, projected)
		Dim sortedBench As List = SortIdsByMinutesAsc(onBench, projected)
		Dim swapCount As Int = Min(Min(sortedPitch.Size, sortedBench.Size), maxSubsPerBreak)
		Dim i As Int
		For i = 0 To swapCount - 1
			Dim pOut As String = sortedPitch.Get(i)
			Dim pIn As String = sortedBench.Get(i)
			Dim swap As Map
			swap.Initialize
			swap.Put("afterQuarter", afterQ)
			swap.Put("playerOut", pOut)
			swap.Put("playerIn", pIn)
			swap.Put("outName", nameById.GetDefault(pOut, "Unknown"))
			swap.Put("inName", nameById.GetDefault(pIn, "Unknown"))
			swaps.Add(swap)
			Dim slot As String = SlotForPlayer(workingLineup, pOut)
			If slot <> "" Then workingLineup.Put(slot, pIn)
		Next
	Next
	
	plan.Put("swaps", swaps)
	plan.Put("autoGenerated", True)
	Dim projectedFinal As Map = ProjectMatchMinutes(startingLineup, plan, squadIds)
	plan.Put("projectedMinutes", projectedFinal)
	Return plan
End Sub

Public Sub FormatPlanLines(plan As Map, nameById As Map) As List
	Dim lines As List
	lines.Initialize
	Dim swaps As List = plan.GetDefault("swaps", EmptyList)
	If swaps.Size = 0 Then
		lines.Add("No quarter swaps planned.")
		Return lines
	End If
	Dim afterQ As Int
	For afterQ = 1 To 3
		Dim bucket As List
		bucket.Initialize
		For Each swap As Map In swaps
			If afterQ = swap.GetDefault("afterQuarter", 0) Then bucket.Add(swap)
		Next
		If bucket.Size > 0 Then
			Dim line As String = "After Q" & afterQ & ": "
			For Each s As Map In bucket
				Dim outN As String = s.GetDefault("outName", nameById.GetDefault(s.GetDefault("playerOut", ""), "?"))
				Dim inN As String = s.GetDefault("inName", nameById.GetDefault(s.GetDefault("playerIn", ""), "?"))
				line = line & outN & " -> " & inN & "; "
			Next
			lines.Add(line)
		End If
	Next
	Return lines
End Sub

Private Sub SortIdsByMinutesDesc(ids As List, minutes As Map) As List
	Dim out As List = CopyStrList(ids)
	Dim i, j As Int
	For i = 0 To out.Size - 2
		For j = i + 1 To out.Size - 1
			Dim a As String = out.Get(i)
			Dim b As String = out.Get(j)
			If minutes.GetDefault(b, 0) > minutes.GetDefault(a, 0) Then
				out.Set(i, b)
				out.Set(j, a)
			End If
		Next
	Next
	Return out
End Sub

Private Sub SortIdsByMinutesAsc(ids As List, minutes As Map) As List
	Dim out As List = CopyStrList(ids)
	Dim i, j As Int
	For i = 0 To out.Size - 2
		For j = i + 1 To out.Size - 1
			Dim a As String = out.Get(i)
			Dim b As String = out.Get(j)
			If minutes.GetDefault(b, 0) < minutes.GetDefault(a, 0) Then
				out.Set(i, b)
				out.Set(j, a)
			End If
		Next
	Next
	Return out
End Sub

Private Sub SlotForPlayer(lineup As Map, playerId As String) As String
	For Each k As String In lineup.Keys
		If lineup.Get(k) = playerId Then Return k
	Next
	Return ""
End Sub

Private Sub ValuesContain(lineup As Map, playerId As String) As Boolean
	For Each v As String In lineup.Values
		If v = playerId Then Return True
	Next
	Return False
End Sub

Private Sub CopyMap(src As Map) As Map
	Dim m As Map
	m.Initialize
	If src.IsInitialized Then
		For Each k As String In src.Keys
			m.Put(k, src.Get(k))
		Next
	End If
	Return m
End Sub

Private Sub CopyStrList(src As List) As List
	Dim out As List
	out.Initialize
	For Each o As Object In src
		out.Add(o)
	Next
	Return out
End Sub

Private Sub CopyListOfMaps(src As List) As List
	Dim out As List
	out.Initialize
	For Each m As Map In src
		out.Add(CopyMap(m))
	Next
	Return out
End Sub

Private Sub EmptyList As List
	Dim l As List
	l.Initialize
	Return l
End Sub

' Season minutes across completed matches for a club player (from stored playerStats + projected sub plans).
Public Sub SeasonMinutesForPlayer(clubId As String, playerId As String, matches As List) As Int
	Dim total As Int = 0
	If playerId = "" Then Return 0
	Dim i As Int
	For i = 0 To matches.Size - 1
		Dim m As Map = matches.Get(i)
		If m.GetDefault("clubId", "") <> clubId Then Continue
		If m.GetDefault("status", "") <> "COMPLETED" Then Continue
		Dim stored As Int = -1
		Dim psMap As Map = m.GetDefault("playerStats", EmptyMap2)
		If psMap.IsInitialized And psMap.ContainsKey(playerId) Then
			Dim ps As Map = psMap.Get(playerId)
			stored = ps.GetDefault("minutesPlayed", -1)
		End If
		If stored >= 0 Then
			total = total + stored
			Continue
		End If
		' Fallback: project from lineup + subPlan
		Dim lineup As Map = m.GetDefault("lineup", m.GetDefault("tacticalLineup", EmptyMap2))
		Dim plan As Map = m.GetDefault("subPlan", EmptyPlan(DEFAULT_MATCH_MINUTES))
		If lineup.IsInitialized = False Or lineup.Size = 0 Then Continue
		Dim squadIds As List
		squadIds.Initialize
		squadIds.Add(playerId)
		Dim mins As Map = ProjectMatchMinutes(lineup, plan, squadIds)
		total = total + mins.GetDefault(playerId, 0)
	Next
	Return total
End Sub

Private Sub EmptyMap2 As Map
	Dim m As Map
	m.Initialize
	Return m
End Sub
