export const FORMATIONS: Record<string, TacticalPosition[]> = {
  '4-4-2': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 15, y: 70 },
    { id: 'lcb', label: 'CB', x: 38, y: 72 },
    { id: 'rcb', label: 'CB', x: 62, y: 72 },
    { id: 'rb', label: 'RB', x: 85, y: 70 },
    { id: 'lm', label: 'LM', x: 15, y: 45 },
    { id: 'lcm', label: 'CM', x: 38, y: 47 },
    { id: 'rcm', label: 'CM', x: 62, y: 47 },
    { id: 'rm', label: 'RM', x: 85, y: 45 },
    { id: 'lst', label: 'ST', x: 35, y: 20 },
    { id: 'rst', label: 'ST', x: 65, y: 20 },
  ],
  '4-3-3': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 15, y: 70 },
    { id: 'lcb', label: 'CB', x: 38, y: 72 },
    { id: 'rcb', label: 'CB', x: 62, y: 72 },
    { id: 'rb', label: 'RB', x: 85, y: 70 },
    { id: 'lcm', label: 'CM', x: 25, y: 48 },
    { id: 'cdm', label: 'DM', x: 50, y: 54 },
    { id: 'rcm', label: 'CM', x: 75, y: 48 },
    { id: 'lw', label: 'LW', x: 20, y: 22 },
    { id: 'st', label: 'ST', x: 50, y: 18 },
    { id: 'rw', label: 'RW', x: 80, y: 22 },
  ],
  '3-5-2': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lcb', label: 'CB', x: 25, y: 72 },
    { id: 'cb', label: 'CB', x: 50, y: 74 },
    { id: 'rcb', label: 'CB', x: 75, y: 72 },
    { id: 'lwb', label: 'LM', x: 15, y: 48 },
    { id: 'rwb', label: 'RM', x: 85, y: 48 },
    { id: 'lcm', label: 'CM', x: 35, y: 50 },
    { id: 'cdm', label: 'DM', x: 50, y: 56 },
    { id: 'rcm', label: 'CM', x: 65, y: 50 },
    { id: 'lst', label: 'ST', x: 35, y: 20 },
    { id: 'rst', label: 'ST', x: 65, y: 20 },
  ],
  '4-2-3-1': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 15, y: 70 },
    { id: 'lcb', label: 'CB', x: 38, y: 72 },
    { id: 'rcb', label: 'CB', x: 62, y: 72 },
    { id: 'rb', label: 'RB', x: 85, y: 70 },
    { id: 'ldm', label: 'DM', x: 35, y: 54 },
    { id: 'rdm', label: 'DM', x: 65, y: 54 },
    { id: 'lam', label: 'LM', x: 20, y: 34 },
    { id: 'cam', label: 'AM', x: 50, y: 34 },
    { id: 'ram', label: 'RM', x: 80, y: 34 },
    { id: 'st', label: 'ST', x: 50, y: 16 },
  ],
  '7-a-side (2-3-1)': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lcb', label: 'CB', x: 30, y: 70 },
    { id: 'rcb', label: 'CB', x: 70, y: 70 },
    { id: 'lm', label: 'LM', x: 20, y: 45 },
    { id: 'cm', label: 'CM', x: 50, y: 45 },
    { id: 'rm', label: 'RM', x: 80, y: 45 },
    { id: 'st', label: 'ST', x: 50, y: 20 },
  ],
  '9-a-side (3-2-3)': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 20, y: 72 },
    { id: 'cb', label: 'CB', x: 50, y: 74 },
    { id: 'rb', label: 'RB', x: 80, y: 72 },
    { id: 'lcm', label: 'CM', x: 35, y: 48 },
    { id: 'rcm', label: 'CM', x: 65, y: 48 },
    { id: 'lw', label: 'LW', x: 20, y: 24 },
    { id: 'st', label: 'ST', x: 50, y: 20 },
    { id: 'rw', label: 'RW', x: 80, y: 24 },
  ],
  '9-a-side (3-3-2)': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 20, y: 72 },
    { id: 'cb', label: 'CB', x: 50, y: 74 },
    { id: 'rb', label: 'RB', x: 80, y: 72 },
    { id: 'lm', label: 'LM', x: 20, y: 48 },
    { id: 'cm', label: 'CM', x: 50, y: 50 },
    { id: 'rm', label: 'RM', x: 80, y: 48 },
    { id: 'lst', label: 'ST', x: 35, y: 22 },
    { id: 'rst', label: 'ST', x: 65, y: 22 },
  ],
  '9-a-side (4-3-1)': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 15, y: 70 },
    { id: 'lcb', label: 'CB', x: 38, y: 72 },
    { id: 'rcb', label: 'CB', x: 62, y: 72 },
    { id: 'rb', label: 'RB', x: 85, y: 70 },
    { id: 'lcm', label: 'CM', x: 25, y: 48 },
    { id: 'cdm', label: 'DM', x: 50, y: 54 },
    { id: 'rcm', label: 'CM', x: 75, y: 48 },
    { id: 'st', label: 'ST', x: 50, y: 20 },
  ],
  '9-a-side (3-4-1)': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'lb', label: 'LB', x: 20, y: 72 },
    { id: 'cb', label: 'CB', x: 50, y: 74 },
    { id: 'rb', label: 'RB', x: 80, y: 72 },
    { id: 'lm', label: 'LM', x: 15, y: 48 },
    { id: 'lcm', label: 'CM', x: 38, y: 50 },
    { id: 'rcm', label: 'CM', x: 62, y: 50 },
    { id: 'rm', label: 'RM', x: 85, y: 48 },
    { id: 'st', label: 'ST', x: 50, y: 22 },
  ],
  '5-a-side (1-2-1)': [
    { id: 'gk', label: 'GK', x: 50, y: 88 },
    { id: 'cb', label: 'CB', x: 50, y: 70 },
    { id: 'lm', label: 'LM', x: 25, y: 45 },
    { id: 'rm', label: 'RM', x: 75, y: 45 },
    { id: 'st', label: 'ST', x: 50, y: 20 },
  ],
};