
export type UserRole = 'ADMIN' | 'PLAYER' | 'COACH' | 'SPECTATOR';
export type ClubType = 'TEAM' | 'SOCIAL';
export type MatchCompetition = 'LEAGUE' | 'FRIENDLY' | 'CUP';

export type PlayerPosition =
  | 'GK' | 'RB' | 'CB' | 'LB' | 'RWB' | 'LWB'
  | 'CDM' | 'CM' | 'CAM' | 'RM' | 'LM'
  | 'RW' | 'LW' | 'CF' | 'ST';

export interface User {
  id: string;
  name: string;
  avatar: string;
  roles: UserRole[];
  squadNumber?: number;
  preferredPosition?: PlayerPosition;
  secondaryPosition?: PlayerPosition;
  phone?: string;
  emergencyContact?: string;
  dateOfBirth?: string;
  medicalNotes?: string;
}

export interface Club {
  id: string;
  name: string;
  logo: string;
  description: string;
  type: ClubType;
  members: User[];
  ownerId: string;
  inviteCode?: string;
  /** Preferred match format for this club (persists across matches) */
  preferredTeamSize?: 5 | 7 | 9 | 11;
  preferredFormation?: string;
}

export interface Match {
  id: string;
  clubId: string;
  title: string;
  date: string;
  meetTime?: string;
  kickOffTime: string;
  location: string;
  status: 'UPCOMING' | 'LIVE' | 'COMPLETED' | 'CANCELLED';
  /** League / Friendly / Cup — used for season booklet and fixtures list */
  competition?: MatchCompetition;
  teamA: PlayerStats[];
  teamB: PlayerStats[];
  scoreA: number;
  scoreB: number;
  signedUpPlayerIds: string[];
  availability?: Record<string, 'CONFIRMED' | 'UNAVAILABLE'>;
  /** Players on the pitch including GK (5 / 7 / 9 / 11) */
  teamSize?: 5 | 7 | 9 | 11;
  formation?: string;
  /** Maps formation slot id (e.g. "GK", "CB1") to player user id */
  lineup?: Record<string, string>;
  /** Planned quarter rotations (fair game-time planner) */
  subPlan?: MatchSubPlan;
  opponentName?: string;
  isHome?: boolean;
  /**
   * Player of the Match votes by award category.
   * coach / opposition maps are voterUserId -> selectedPlayerId.
   * fans may be individual ballots (legacy) and/or fanCounts (playerId -> vote total).
   * Legacy flat Record<string, string> is normalized to `fans` on read.
   */
  potmVotes?: PotmVotes;
  aiSummary?: string;
  /** Photo URLs for the season booklet / end-of-season PDF */
  photoUrls?: string[];
}

/** Coach's / Fan's / Opposition's Player of the Match */
export type PotmCategory = 'coach' | 'fans' | 'opposition';

export interface PotmVotes {
  coach?: Record<string, string>;
  /** Individual fan ballots: voterUserId -> selectedPlayerId */
  fans?: Record<string, string>;
  /** Manual fan tallies: playerUserId -> number of votes (for when fans vote offline) */
  fanCounts?: Record<string, number>;
  opposition?: Record<string, string>;
}

export interface FormationSlot {
  id: string;
  label: PlayerPosition;
  /** 0–100 from left of pitch */
  x: number;
  /** 0–100 from top of pitch (0 = own goal / GK) */
  y: number;
}

/** One planned swap at a quarter break (after Q1 / Q2 / Q3). */
export interface PlannedSub {
  /** Swap happens after this quarter ends (before the next). */
  afterQuarter: 1 | 2 | 3;
  playerOut: string;
  playerIn: string;
}

/** Coach rotation plan: 4 equal quarters, optional auto-proposed swaps. */
export interface MatchSubPlan {
  /** Total match length in minutes (split equally across 4 quarters). Default 60. */
  matchMinutes: number;
  quarters: 4;
  swaps: PlannedSub[];
  autoGenerated?: boolean;
}

export interface PlayerStats {
  userId: string;
  name: string;
  goals: number;
  assists: number;
  yellowCards: number;
  redCards: number;
}

export type EventType = 'GOAL' | 'SUB' | 'COMMENT' | 'MEDIA' | 'START' | 'HALF_TIME' | 'SECOND_HALF' | 'END' | 'CORNER' | 'FREE_KICK' | 'PENALTY' | 'YELLOW_CARD' | 'RED_CARD' | 'CANCELLED';

export interface FeedEvent {
  id: string;
  matchId: string;
  userId: string;
  userName: string;
  type: EventType;
  timestamp: Date;
  content: string;
  mediaUrl?: string;
  details?: {
    playerIn?: string;
    playerOut?: string;
    scorer?: string;
    assist?: string;
    team?: 'A' | 'B';
  };
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  text: string;
  timestamp: Date;
}

export interface AppNotification {
  id: string;
  title: string;
  body: string;
  timestamp: Date;
  isRead: boolean;
  type: 'MATCH_START' | 'GOAL' | 'SUB' | 'SYSTEM';
  linkId?: string;
}
