import React, { useMemo, useState } from 'react';
import { ArrowRightLeft, Users, AlertTriangle, Plus, Trash2, Printer } from 'lucide-react';
import { Match, MatchSubPlan, PlannedSub, User } from '../types';
import { formatMinutes } from '../lib/playingMinutes';
import {
  DEFAULT_MATCH_MINUTES,
  emptySubPlan,
  lineupsByQuarter,
  minutesPerQuarter,
  planFairnessStats,
  projectMatchMinutes,
  Quarter,
} from '../lib/subPlan';
import { printSubPlan } from '../lib/subPlanPrint';

const MATCH_LENGTH_OPTIONS = [40, 50, 60, 70, 80, 90];

interface SubPlanPanelProps {
  match: Match;
  confirmedSquad: User[];
  startingLineup: Record<string, string>;
  seasonMinutes: Record<string, number>;
  canEdit: boolean;
  clubName?: string;
  onSave: (plan: MatchSubPlan | undefined) => void;
  onGoToLineup: () => void;
}

function playerName(player: User | undefined, fallbackId: string): string {
  if (!player) return 'Unknown';
  return player.squadNumber != null ? `#${player.squadNumber} ${player.name}` : player.name;
}

/** Dropdown / chip label: name · position (if any) · season minutes · plan minutes. */
function playerOptionLabel(
  player: User | undefined,
  fallbackId: string,
  opts: { seasonMins: number; matchMins: number; pitchPos?: string }
): string {
  const name = playerName(player, fallbackId);
  const pos = opts.pitchPos || player?.preferredPosition || player?.secondaryPosition;
  const parts = [name];
  if (pos) parts.push(pos);
  parts.push(`${formatMinutes(opts.seasonMins)} season`);
  parts.push(`${formatMinutes(opts.matchMins)} plan`);
  return parts.join(' · ');
}

function slotForPlayer(lineup: Record<string, string>, playerId: string): string | undefined {
  return Object.entries(lineup).find(([, pid]) => pid === playerId)?.[0];
}

export const SubPlanPanel: React.FC<SubPlanPanelProps> = ({
  match,
  confirmedSquad,
  startingLineup,
  seasonMinutes,
  canEdit,
  clubName,
  onSave,
  onGoToLineup,
}) => {
  const plan = match.subPlan || emptySubPlan(DEFAULT_MATCH_MINUTES);
  const starterIds = useMemo(
    () => Object.values(startingLineup).filter(Boolean),
    [startingLineup]
  );
  const squadIds = useMemo(() => confirmedSquad.map(p => p.id), [confirmedSquad]);
  const playerById = useMemo(() => {
    const map = new Map<string, User>();
    confirmedSquad.forEach(p => map.set(p.id, p));
    return map;
  }, [confirmedSquad]);

  const [draftOut, setDraftOut] = useState<Record<1 | 2 | 3, string>>({ 1: '', 2: '', 3: '' });
  const [draftIn, setDraftIn] = useState<Record<1 | 2 | 3, string>>({ 1: '', 2: '', 3: '' });

  const projected = useMemo(
    () => projectMatchMinutes(startingLineup, plan, squadIds),
    [startingLineup, plan, squadIds]
  );

  const byQuarter = useMemo(
    () => lineupsByQuarter(startingLineup, plan.swaps || []),
    [startingLineup, plan.swaps]
  );

  const fairness = useMemo(() => planFairnessStats(projected, squadIds), [projected, squadIds]);
  const perQ = minutesPerQuarter(plan);
  const lineupReady = starterIds.length > 0;

  const persist = (next: MatchSubPlan) => onSave(next);

  const handleMatchMinutes = (mins: number) => {
    if (!canEdit) return;
    persist({ ...plan, matchMinutes: mins, autoGenerated: false });
  };

  const handleClear = () => {
    if (!canEdit) return;
    persist(emptySubPlan(plan.matchMinutes || DEFAULT_MATCH_MINUTES));
  };

  const handlePrint = () => {
    printSubPlan({
      match,
      plan,
      startingLineup,
      confirmedSquad,
      seasonMinutes,
      clubName,
    });
  };

  const removeSwap = (index: number) => {
    if (!canEdit) return;
    const swaps = [...(plan.swaps || [])];
    swaps.splice(index, 1);
    persist({ ...plan, swaps, autoGenerated: false });
  };

  const addSwap = (afterQuarter: 1 | 2 | 3) => {
    if (!canEdit) return;
    const playerOut = draftOut[afterQuarter];
    const playerIn = draftIn[afterQuarter];
    if (!playerOut || !playerIn || playerOut === playerIn) return;

    const lineupBefore = byQuarter[afterQuarter];
    const onPitch = new Set(Object.values(lineupBefore));
    if (!onPitch.has(playerOut) || onPitch.has(playerIn)) return;

    const swaps = [...(plan.swaps || []), { afterQuarter, playerOut, playerIn } satisfies PlannedSub];
    persist({ ...plan, swaps, autoGenerated: false });
    setDraftOut(prev => ({ ...prev, [afterQuarter]: '' }));
    setDraftIn(prev => ({ ...prev, [afterQuarter]: '' }));
  };

  const rows = useMemo(() => {
    return squadIds
      .map(id => {
        const player = playerById.get(id);
        const matchMins = projected[id] || 0;
        const seasonSoFar = seasonMinutes[id] || 0;
        return {
          id,
          player,
          matchMins,
          seasonSoFar,
          seasonAfter: seasonSoFar + matchMins,
        };
      })
      .sort(
        (a, b) =>
          a.matchMins - b.matchMins ||
          a.seasonSoFar - b.seasonSoFar ||
          (a.player?.name || '').localeCompare(b.player?.name || '')
      );
  }, [squadIds, playerById, projected, seasonMinutes]);

  const maxBar = Math.max(...rows.map(r => r.seasonAfter), 1);

  /** Sort candidates for OFF (most minutes first) / ON (fewest first; prefer position match). */
  const sortOffCandidates = (ids: string[]) =>
    [...ids].sort((a, b) => {
      const ma = (projected[a] || 0) + (seasonMinutes[a] || 0);
      const mb = (projected[b] || 0) + (seasonMinutes[b] || 0);
      if (mb !== ma) return mb - ma;
      return playerName(playerById.get(a), a).localeCompare(playerName(playerById.get(b), b));
    });

  const sortOnCandidates = (players: User[], preferPos?: string) =>
    [...players].sort((a, b) => {
      if (preferPos) {
        const aMatch =
          a.preferredPosition === preferPos || a.secondaryPosition === preferPos ? 0 : 1;
        const bMatch =
          b.preferredPosition === preferPos || b.secondaryPosition === preferPos ? 0 : 1;
        if (aMatch !== bMatch) return aMatch - bMatch;
      }
      const ma = (projected[a.id] || 0) + (seasonMinutes[a.id] || 0);
      const mb = (projected[b.id] || 0) + (seasonMinutes[b.id] || 0);
      if (ma !== mb) return ma - mb;
      return a.name.localeCompare(b.name);
    });

  if (confirmedSquad.length === 0) {
    return (
      <div className="p-10 text-center bg-white rounded-[2rem] border border-dashed border-slate-200">
        <Users className="w-8 h-8 text-slate-300 mx-auto mb-3" />
        <p className="text-sm font-bold text-slate-500">Confirm players first</p>
        <p className="text-xs text-slate-400 mt-1">Mark availability, set a lineup, then plan subs.</p>
      </div>
    );
  }

  if (!lineupReady) {
    return (
      <div className="p-10 text-center bg-white rounded-[2rem] border border-dashed border-slate-200">
        <ArrowRightLeft className="w-8 h-8 text-slate-300 mx-auto mb-3" />
        <p className="text-sm font-bold text-slate-500">Set a starting lineup</p>
        <p className="text-xs text-slate-400 mt-1">
          The sub planner needs kick-off XI and bench so you can plan rotations.
        </p>
        <button
          type="button"
          onClick={onGoToLineup}
          className="mt-4 px-5 py-2.5 bg-blue-600 text-white rounded-xl text-[10px] font-black uppercase tracking-widest"
        >
          Go to Lineup
        </button>
      </div>
    );
  }

  const benchCount = Math.max(0, squadIds.length - starterIds.length);

  return (
    <div className="space-y-6">
      <div className="text-center py-2">
        <div className="inline-flex p-4 bg-orange-50 text-orange-600 rounded-[1.5rem] mb-3">
          <ArrowRightLeft className="w-7 h-7" />
        </div>
        <h2 className="text-xl font-black text-slate-900 tracking-tight">Sub planner</h2>
        <p className="text-sm text-slate-500 font-medium mt-1 max-w-md mx-auto">
          4 quarters · pick swaps using position and minutes. Plan is a guide — log real SUBs live when needed.
        </p>
      </div>

      <div className="bg-white rounded-2xl border border-slate-100 p-4 space-y-4">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div className="space-y-1.5">
            <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1">
              Match length
            </label>
            <div className="flex flex-wrap gap-1.5">
              {MATCH_LENGTH_OPTIONS.map(mins => (
                <button
                  key={mins}
                  type="button"
                  disabled={!canEdit}
                  onClick={() => handleMatchMinutes(mins)}
                  className={`px-3 py-2 rounded-xl text-[10px] font-black tracking-widest transition-all border ${
                    plan.matchMinutes === mins
                      ? 'bg-slate-900 text-white border-slate-900'
                      : 'bg-white text-slate-500 border-slate-200 hover:border-slate-300'
                  } disabled:opacity-60`}
                >
                  {mins}′
                </button>
              ))}
            </div>
            <p className="text-[10px] text-slate-400 font-medium px-1">
              {formatMinutes(Math.round(perQ))} per quarter · {starterIds.length} on pitch · {benchCount} bench
            </p>
          </div>

          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center gap-2 px-4 py-2.5 bg-white text-slate-700 border border-slate-200 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-50 transition-all"
              title="Opens print dialog — choose Save as PDF to download"
            >
              <Printer className="w-3.5 h-3.5" />
              Print / PDF
            </button>
            {canEdit && (plan.swaps || []).length > 0 && (
              <button
                type="button"
                onClick={handleClear}
                className="px-4 py-2.5 bg-slate-100 text-slate-600 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-200 transition-all"
              >
                Clear plan
              </button>
            )}
          </div>
        </div>

        {!canEdit && (
          <p className="text-[10px] text-slate-400 font-medium">Only coaches and admins can edit the plan.</p>
        )}

        {benchCount === 0 && (
          <div className="flex items-start gap-2 rounded-xl bg-amber-50 border border-amber-100 px-3 py-2.5 text-[11px] text-amber-800 font-medium">
            <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
            Everyone confirmed is in the starting lineup — no bench to rotate. Confirm more players or leave someone on the bench.
          </div>
        )}

        {fairness.unused.length > 0 && (plan.swaps || []).length > 0 && (
          <div className="flex items-start gap-2 rounded-xl bg-red-50 border border-red-100 px-3 py-2.5 text-[11px] text-red-700 font-medium">
            <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
            {fairness.unused.length} player{fairness.unused.length === 1 ? '' : 's'} still get 0′ — add swaps to get them on.
          </div>
        )}

        {(plan.swaps || []).length > 0 && fairness.unused.length === 0 && (
          <p className="text-[11px] text-slate-500 font-medium px-1">
            Spread {formatMinutes(fairness.min)}–{formatMinutes(fairness.max)} this match
          </p>
        )}
      </div>

      {/* Quarter timeline */}
      <div className="space-y-3">
        {([1, 2, 3, 4] as Quarter[]).map(q => {
          const onPitchIds = Object.values(byQuarter[q]);
          const afterBreak = q < 4 ? (q as 1 | 2 | 3) : null;
          const breakSwaps = afterBreak
            ? (plan.swaps || [])
                .map((s, index) => ({ ...s, index }))
                .filter(s => s.afterQuarter === afterBreak)
            : [];

          const outPlayer = afterBreak ? playerById.get(draftOut[afterBreak]) : undefined;
          const preferPos =
            outPlayer?.preferredPosition || outPlayer?.secondaryPosition || undefined;

          return (
            <div key={q} className="space-y-2">
              <div className="bg-white rounded-2xl border border-slate-100 overflow-hidden">
                <div className="px-4 py-2.5 bg-slate-50/80 border-b border-slate-100 flex items-center justify-between">
                  <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-600">
                    Q{q} · {formatMinutes(Math.round(perQ))}
                  </h3>
                  <span className="text-[10px] font-bold text-slate-400">
                    {onPitchIds.length} on pitch
                  </span>
                </div>
                <div className="px-4 py-3 flex flex-wrap gap-1.5">
                  {onPitchIds.map(id => {
                    const p = playerById.get(id);
                    const pitchPos = slotForPlayer(byQuarter[q], id);
                    return (
                      <span
                        key={`${q}-${id}`}
                        className="inline-flex items-center gap-1.5 px-2 py-1 rounded-lg bg-slate-50 border border-slate-100 text-[11px] font-bold text-slate-800"
                        title={playerOptionLabel(p, id, {
                          seasonMins: seasonMinutes[id] || 0,
                          matchMins: projected[id] || 0,
                          pitchPos: pitchPos || p?.preferredPosition,
                        })}
                      >
                        <img
                          src={p?.avatar || `https://i.pravatar.cc/100?u=${id}`}
                          className="w-5 h-5 rounded-md object-cover"
                          alt=""
                        />
                        {playerName(p, id)}
                        {(p?.preferredPosition || pitchPos) && (
                          <span className="text-[9px] font-black text-slate-400 uppercase">
                            {p?.preferredPosition || pitchPos}
                          </span>
                        )}
                        <span className="text-[9px] font-black tabular-nums text-slate-400">
                          {formatMinutes(seasonMinutes[id] || 0)}
                        </span>
                      </span>
                    );
                  })}
                </div>
              </div>

              {afterBreak && (
                <div className="ml-2 pl-3 border-l-2 border-orange-200 space-y-2">
                  <p className="text-[10px] font-black uppercase tracking-widest text-orange-600">
                    Break after Q{afterBreak}
                  </p>
                  {breakSwaps.length === 0 ? (
                    <p className="text-[11px] text-slate-400 font-medium">No swaps planned</p>
                  ) : (
                    <div className="space-y-1.5">
                      {breakSwaps.map(swap => (
                        <div
                          key={swap.index}
                          className="flex items-center gap-2 bg-white border border-slate-100 rounded-xl px-3 py-2"
                        >
                          <span className="text-[11px] font-bold text-red-600 truncate flex-1">
                            ↓ {playerName(playerById.get(swap.playerOut), swap.playerOut)}
                          </span>
                          <ArrowRightLeft className="w-3.5 h-3.5 text-slate-300 shrink-0" />
                          <span className="text-[11px] font-bold text-green-600 truncate flex-1 text-right">
                            ↑ {playerName(playerById.get(swap.playerIn), swap.playerIn)}
                          </span>
                          {canEdit && (
                            <button
                              type="button"
                              onClick={() => removeSwap(swap.index)}
                              className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg shrink-0"
                              aria-label="Remove swap"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          )}
                        </div>
                      ))}
                    </div>
                  )}

                  {canEdit && (
                    <div className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center">
                      <select
                        value={draftOut[afterBreak]}
                        onChange={e =>
                          setDraftOut(prev => ({ ...prev, [afterBreak]: e.target.value }))
                        }
                        className="flex-1 bg-white border border-slate-200 rounded-xl px-3 py-2 text-[11px] font-bold text-slate-700"
                      >
                        <option value="">Player off…</option>
                        {sortOffCandidates(Object.values(byQuarter[afterBreak])).map(id => {
                          const p = playerById.get(id);
                          return (
                            <option key={`out-${afterBreak}-${id}`} value={id}>
                              {playerOptionLabel(p, id, {
                                seasonMins: seasonMinutes[id] || 0,
                                matchMins: projected[id] || 0,
                                pitchPos: p?.preferredPosition,
                              })}
                            </option>
                          );
                        })}
                      </select>
                      <select
                        value={draftIn[afterBreak]}
                        onChange={e =>
                          setDraftIn(prev => ({ ...prev, [afterBreak]: e.target.value }))
                        }
                        className="flex-1 bg-white border border-slate-200 rounded-xl px-3 py-2 text-[11px] font-bold text-slate-700"
                      >
                        <option value="">Player on…</option>
                        {sortOnCandidates(
                          confirmedSquad.filter(
                            p => !Object.values(byQuarter[afterBreak]).includes(p.id)
                          ),
                          preferPos
                        ).map(p => (
                          <option key={`in-${afterBreak}-${p.id}`} value={p.id}>
                            {playerOptionLabel(p, p.id, {
                              seasonMins: seasonMinutes[p.id] || 0,
                              matchMins: projected[p.id] || 0,
                              pitchPos: p.preferredPosition,
                            })}
                          </option>
                        ))}
                      </select>
                      <button
                        type="button"
                        onClick={() => addSwap(afterBreak)}
                        disabled={!draftOut[afterBreak] || !draftIn[afterBreak]}
                        className="inline-flex items-center justify-center gap-1.5 px-3 py-2 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest disabled:opacity-40"
                      >
                        <Plus className="w-3.5 h-3.5" /> Add
                      </button>
                    </div>
                  )}
                  {canEdit && preferPos && (
                    <p className="text-[10px] text-slate-400 font-medium">
                      Bench list sorted by position match ({preferPos}) then fewest minutes
                    </p>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Minutes impact table */}
      <div className="bg-white rounded-2xl border border-slate-100 overflow-hidden">
        <div className="px-4 py-3 border-b border-slate-100">
          <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-500">
            Game time impact
          </h3>
          <p className="text-[11px] text-slate-400 font-medium mt-0.5">
            This match (planned) · season so far · after this plan
          </p>
        </div>
        <div className="divide-y divide-slate-50">
          {rows.map(row => (
            <div key={row.id} className="px-4 py-3 flex items-center gap-3">
              <img
                src={row.player?.avatar || `https://i.pravatar.cc/100?u=${row.id}`}
                className="w-9 h-9 rounded-xl object-cover shrink-0"
                alt=""
              />
              <div className="min-w-0 flex-1 space-y-1.5">
                <div className="flex items-center justify-between gap-2">
                  <p className="text-[12px] font-black text-slate-900 truncate">
                    {playerName(row.player, row.id)}
                    {row.player?.preferredPosition ? (
                      <span className="ml-1.5 text-[9px] font-black uppercase tracking-widest text-slate-400">
                        {row.player.preferredPosition}
                      </span>
                    ) : null}
                  </p>
                  <div className="flex items-center gap-2 shrink-0 text-[11px] font-black tabular-nums">
                    <span className="text-orange-600">{formatMinutes(row.matchMins)}</span>
                    <span className="text-slate-300">·</span>
                    <span className="text-slate-400">{formatMinutes(row.seasonSoFar)}</span>
                    <span className="text-slate-300">→</span>
                    <span className="text-slate-900">{formatMinutes(row.seasonAfter)}</span>
                  </div>
                </div>
                <div className="h-1.5 rounded-full bg-slate-100 overflow-hidden">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-slate-300 to-orange-400"
                    style={{ width: `${Math.max(4, (row.seasonAfter / maxBar) * 100)}%` }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
